
set(MEDIPACK_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/../include")
set(MEDIPACK_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}/../src")
set(MEDIPACK_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}/../cmake")

file(READ "${MEDIPACK_INCLUDE_DIR}/medi/medi.hpp" ver)

string(REGEX MATCH "MEDI_MAJOR_VERSION ([0-9]*)" _ ${ver})
set(MEDIPACK_MAJOR_VERSION ${CMAKE_MATCH_1})

string(REGEX MATCH "MEDI_MINOR_VERSION ([0-9]*)" _ ${ver})
set(MEDIPACK_MINOR_VERSION ${CMAKE_MATCH_1})

string(REGEX MATCH "MEDI_BUILD_VERSION ([0-9]*)" _ ${ver})
set(MEDIPACK_BUILD_VERSION ${CMAKE_MATCH_1})

set(MEDIPACK_VERSION "${MEDIPACK_MAJOR_VERSION}.${MEDIPACK_MINOR_VERSION}.${MEDIPACK_BUILD_VERSION}")
set(MEDIPACK_NAME "MeDiPack")
set(MEDIPACK_CXX_VERSION "cxx_std_11")
